# Generated by Django 5.1.5 on 2025-01-31 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Halfling', 'Halfling'), ('Half-Elf', 'Half-Elf'), ('Half-Orc', 'Half-Orc'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], max_length=255)),
                ('adventurer_class', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('strength', models.PositiveSmallIntegerField(default=8)),
                ('dexterity', models.PositiveSmallIntegerField(default=8)),
                ('constitution', models.PositiveSmallIntegerField(default=8)),
                ('intelligence', models.PositiveSmallIntegerField(default=8)),
                ('wisdom', models.PositiveSmallIntegerField(default=8)),
                ('charisma', models.PositiveSmallIntegerField(default=8)),
                ('hp_base', models.PositiveSmallIntegerField(default=10)),
                ('hp_current', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
    ]
