# Generated by Django 5.1.5 on 2025-02-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='adventurer_class',
            field=models.CharField(choices=[('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Fighter', 'Fighter'), ('Rogue', 'Rogue'), ('Wizard', 'Wizard')], max_length=255),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='species',
            field=models.CharField(choices=[('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Halfling', 'Halfling'), ('Human', 'Human')], max_length=255),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.party'),
        ),
    ]
